name: Build and Deploy to itch.io

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: test-project
  PROJECT_PATH: games/test-project

on:
  pull_request:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p ${{ env.PROJECT_PATH }}/build/web
          cd ${{ env.PROJECT_PATH }}
          godot --headless --verbose --export-release "HTML5" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: ${{ env.PROJECT_PATH }}/build/web

  
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: netlify
      url: ${{ steps.deployment.outputs.deploy-url }}
    steps:
      - run: find ./ -type f
      - name: Download Artifact
        uses: actions/download-artifact@v4
      - run: find ./ -type f
      - name: Deploy to Netlify
        id: deployment
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

    