name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  godot-ci:
    uses: watsutatsu/actions/.github/workflows/godot-ci.yml@apaz/godot-ci
    with:
      godot_version: 4.2.2
      export_name: test-project
      project_path: games/test-project
